apiVersion: apps/v1
kind: Deployment
metadata:
  name: rajratna-deployment
  labels:
    app: rajratna
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rajratna
  template:
    metadata:
      labels:
        app: rajratna
    spec:
      containers:
        - name: rajratna-container
          image: ednvk/rajratna-site:latest   # Replace with your Docker Hub image if needed
          ports:
            - containerPort: 80
